services:
  app:
    image: laravelsail/php82-composer
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    command: sh -c "composer install && php artisan key:generate && php artisan serve --host=0.0.0.0 --port=80"
    environment:
      APP_ENV: production
      APP_DEBUG: false
      APP_URL: http://localhost
      APP_KEY: 
      DB_CONNECTION: mysql
      DB_HOST: 
      DB_PORT: 3306
      DB_DATABASE: 
      DB_USERNAME: 
      DB_PASSWORD: 
