version: '3.8'

services:
  app:
    image: laravelsail/php82-composer
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    command: sh -c "composer install && php artisan config:cache && php artisan serve --host=0.0.0.0 --port=8000"
    
      

