version: '3.8'

services:
  app:
    build: .
    working_dir: /var/www/html
    labels:
      - "coolify.port=8000"
      - "coolify.service.public=true"
      - "coolify.service.name=app"
    environment:
      - APP_ENV
      - APP_DEBUG
      - APP_URL
      - APP_KEY
      - DB_CONNECTION
      - DB_HOST
      - DB_PORT
      - DB_DATABASE
      - DB_USERNAME
      - DB_PASSWORD
