services:
  app:
    image: laravelsail/php82-composer
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    command: sh -c "composer install && php artisan key:generate && php artisan serve --host=0.0.0.0 --port=80"
    environment:
      APP_ENV: production
      APP_DEBUG: false
      APP_URL: http://localhost
      APP_KEY: base64:sjW7e/wdG2kKQJePQw9rGC3RMGYekUtR8Sv9AQwadKo=
      DB_CONNECTION: mysql
      DB_HOST: 167.86.90.186
      DB_PORT: 3306
      DB_DATABASE: bdcoolify
      DB_USERNAME: mysql
      DB_PASSWORD: Pablo2022
